default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /run/mysqld/mysqld.sock

development:
  <<: *default
  database: gdsa

test:
  <<: *default
  database: gdsa_test

staging:
  <<: *default
  socket: /var/run/mysql-default/mysqld.sock
  database: gdsa
  username: gdsa
  password: <%= ENV['GDSA_DATABASE_PASSWORD'] %>

production:
  <<: *default
  socket: /var/run/mysql-default/mysqld.sock
  database: gdsa
  username: gdsa
  password: <%= ENV['GDSA_DATABASE_PASSWORD'] %>
